- src/main/resources/templates/layouts/baseLayout.html
Update CSS imports to use up-to-date govuk style for links
LFA-1070
> Update CDN imports

- logging.properties
- start.sh
Due to issues in live with creating a payment session from the lfp service, this PR turns on logging for the http-client as per https://www.baeldung.com/google-http-client#logging
> turn on http-client logging

- src/main/java/uk/gov/companieshouse/web/lfp/controller/lfp/ViewPenaltiesController.java
- src/test/java/uk/gov/companieshouse/web/lfp/controller/lfp/ViewPenaltiesControllerTest.java
Send flag to payments service to redirect directly to GovPay
> Add query paramater to skip summary page when calling payments service

- src/main/resources/templates/fragments/header.html
pulled the header fragment out of common web java and changed the href to /late-filing-penalty for gds assessment
> add header fragment that redirects banner link to LFP app

- pom.xml
This new version of the `web-security-java` handles the new fine grain scopes (when the relevant feature flag is on)
Resolves FA-867
> Upgrade library to use new fine grain scopes

- src/main/java/uk/gov/companieshouse/web/lfp/controller/lfp/SignOutController.java
Resolves [BI-11813](https://companieshouse.atlassian.net/browse/BI-11813)
When the user does not select an action in the sign out page, it shows an error. Once this error is shown, the user can now click the back button to return them to the previous page.
> Add functionality to return user back to previous page after error throws

- src/main/java/uk/gov/companieshouse/web/lfp/controller/lfp/LFPStartController.java
- src/main/resources/templates/layouts/baseLayout.html
Resolves [BI-12481](https://companieshouse.atlassian.net/browse/BI-12481)
-  Remove the idle sign out functionality by removing call to cdn script
- As an add on to previous work in [BI-12376-](https://github.com/companieshouse/lfp-pay-web/pull/131)  add extra log message to ensure that service exception is logged on start controller if issue with connecting to financial service. 
[BI-12481]: https://companieshouse.atlassian.net/browse/BI-12481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-12481-remove idle signout scripts

- pom.xml
https://companieshouse.atlassian.net/browse/IE-254
The app was using jackson-databind 2.11 (from Spring) and jackson-datatype-jsr310 2.12 (from structured-logging). These two jackson packages calls each other so the difference caused an issue where jsr310 called a method that didn't exist in databind.
Updated the Spring version so the versions of jackson is compatible.
> IE-254 Fix issue with handling empty date strings

- README.md
- src/main/java/uk/gov/companieshouse/web/pps/config/FeatureFlagConfigurationProperties.java
- src/main/java/uk/gov/companieshouse/web/pps/config/PenaltyConfigurationProperties.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferPenaltyReferenceController.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferSanctionsDetailsController.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/EnterDetailsController.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/PenaltyRefStartsWithController.java
- src/main/java/uk/gov/companieshouse/web/pps/models/PenaltyReferenceChoice.java
- src/main/java/uk/gov/companieshouse/web/pps/util/FeatureFlagChecker.java
- src/main/resources/ValidationMessages.properties
- src/main/resources/application.properties
- src/main/resources/templates/pps/bankTransferPenaltyReference.html
- src/main/resources/templates/pps/penaltyRefStartsWith.html
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferPenaltyReferenceControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferSanctionsDetailsControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/EnterDetailsControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/PenaltyRefStartsWithControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/util/FeatureFlagCheckerTest.java
[SAN-63](https://companieshouse.atlassian.net/browse/SAN-63) Add FeatureFlagChecker.isPenaltyRefEnabled to ensure that SANCTIONS is disabled by default in application.properties
* Env var: `FEATURE_FLAG_PENALTY_REF_ENABLED_SANCTIONS_191224=false`
* Add PENALTY_REFERENCE_CHOICE_ATTR model assertions to tests
* Update README Configuration - Env: `FEATURE_FLAG_PENALTY_REF_ENABLED_SANCTIONS_191224` Feature flag to enable Penalty Payment for Sanctions
[SAN-63]: https://companieshouse.atlassian.net/browse/SAN-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAN-63 Add FEATURE_FLAG_PENALTY_REF_ENABLED_SANCTIONS_191224=false

- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferPenaltyReferenceController.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferSanctionsDetailsController.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/PenaltyRefStartsWithController.java
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferPenaltyReferenceControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferSanctionsDetailsControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/PenaltyRefStartsWithControllerTest.java
[SAN-198](https://companieshouse.atlassian.net/browse/SAN-198) Redirect to late filing details when `FEATURE_FLAG_PENALTY_REF_ENABLED_SANCTIONS_191224=false` on 'penaltyRefStartsWith' screen
* Pay by bank transfer shows both LATE_FILING, SANCTIONS
* Suppress SONARJAVA (java:S3958) - Intermediate Stream methods should not be left unused
We need to use the latest Java Rules since we are using Java 21.  It should already be fixed here to support Stream#toList() method introduced in JDK16 - SONARJAVA-3746: Extend rule S2201 to support 'Stream' non-void terminal methods
[SAN-198]: https://companieshouse.atlassian.net/browse/SAN-198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAN-198 Redirect to late filing details when `FEATURE_FLAG_PENALTY_REF_ENABLED_SANCTIONS_191224=false` on 'penaltyRefStartsWith' screen

- src/main/resources/application.properties
- src/main/resources/templates/pps/confirmationPage.html
- src/main/resources/templates/pps/home.html
[SAN-196](https://companieshouse.atlassian.net/browse/SAN-196) Matomo config - Pay another penalty
* Also correct the "Start now" event / goal on the homepage
Depends on https://github.com/companieshouse/ecs-service-configs-dev/pull/931
[SAN-196]: https://companieshouse.atlassian.net/browse/SAN-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAN-196 Matomo config - Pay another penalty * Also correct the "Start now" event / goal on the homepage

- src/main/java/uk/gov/companieshouse/web/pps/PPSWebApplication.java
- src/main/java/uk/gov/companieshouse/web/pps/config/PenaltyConfigurationProperties.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/BaseController.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferSanctionsDetailsController.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ConfirmationController.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/EnterDetailsController.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/PenaltyPaidController.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/SignOutController.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/StartController.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/UnscheduledServiceDownController.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ViewPenaltiesController.java
- src/main/java/uk/gov/companieshouse/web/pps/exception/GlobalExceptionHandler.java
- src/main/java/uk/gov/companieshouse/web/pps/security/WebSecurity.java
- src/main/java/uk/gov/companieshouse/web/pps/util/PenaltyUtils.java
- src/main/resources/application.properties
- src/main/resources/templates/pps/unscheduledServiceDown.html
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferSanctionsDetailsControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/ConfirmationControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/EnterDetailsControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/PenaltyPaidControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/SignOutControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/StartControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/UnscheduledServiceDownControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/controller/pps/ViewPenaltiesControllerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/exception/GlobalExceptionHandlerTest.java
- src/test/java/uk/gov/companieshouse/web/pps/security/WebsecurityTests.java
- src/test/java/uk/gov/companieshouse/web/pps/util/PenaltyUtilsTest.java
Set up page for STOP screen - service is down (unscheduled)
> SAN-140 STOP screen - service is down (unscheduled)

- pom.xml
Updated the libraries we use that have the logback-core dependency
- structured-logging
- java-session-handler
- web-security-java
All reviewed by other projects and committed and added new versions to the project.
Excluded 'logback-core' from 'spring-boot-starter-validation' as the latest version without the vulnerability '1.5.16' has breaking changes in it, it is not a true patch release (comment in ticket of issues).
> SAN-201: Fix security vulnerability

- src/main/java/uk/gov/companieshouse/web/pps/config/PenaltyConfigurationProperties.java
- src/main/java/uk/gov/companieshouse/web/pps/controller/pps/SignOutController.java
- src/main/resources/application.properties
For ticket: https://companieshouse.atlassian.net/browse/SAN-316
Updating where user is taken to whenever clicking "yes" and confirming sign out. For lower environments (CIDEV and Local) the user will be taken to the "Search the register" page and in live they should be taken to the GDS home page.
> SAN-316-Sign-Out-Redirect-to-GDS updating signed out url

- pom.xml
- src/main/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PayablePenaltyServiceImpl.java
- src/main/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PenaltyPaymentServiceImpl.java
- src/test/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PayablePenaltyServiceImplTest.java
- src/test/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PenaltyPaymentServiceImplTest.java
- src/test/java/uk/gov/companieshouse/web/pps/util/PPSTestUtility.java
[SAN-66](https://companieshouse.atlassian.net/browse/SAN-66) Replace `/financial-penalties` with `/penalties` path due to AWS LB listener rule
[SAN-66]: https://companieshouse.atlassian.net/browse/SAN-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAN-66 Replace /financial-penalties with /penalties path due to AWS LB listener rule

- README.md
- src/main/resources/application.properties
- src/main/resources/templates/pps/onlinePaymentUnavailable.html
- src/main/resources/templates/pps/serviceUnavailable.html
- src/main/resources/templates/pps/unscheduledServiceDown.html
Adding in matomo tracking for stop screens, https://companieshouse.atlassian.net/browse/SAN-299
Linked to:
https://github.com/companieshouse/docker-chs-development/pull/1675
https://github.com/companieshouse/ecs-service-configs-dev/pull/1120
> SAN-299-Matomo-STOP-screens

- pom.xml
Upgrade spring-boot to latest version to fix security issue
spring-security-core-6.4.3.jar: CVE-2025-22223(6.9)
> SAN-391: Upgrade spring-boot to latest version to fix security issue

- src/main/java/uk/gov/companieshouse/web/pps/PPSWebApplication.java
- src/main/java/uk/gov/companieshouse/web/pps/security/WebSecurity.java
- src/test/java/uk/gov/companieshouse/web/pps/security/WebSecurityTests.java
[SAN-419](https://companieshouse.atlassian.net/browse/SAN-419) Update WebSecurity to remove old bankTransferSecurityFilterChain following recent removal of the bank-transfer pages
[SAN-419]: https://companieshouse.atlassian.net/browse/SAN-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAN-419 Update WebSecurity to remove old bankTransferSecurityFilterChain following recent removal of the bank-transfer pages

- pom.xml
[SAN-420](https://companieshouse.atlassian.net/browse/SAN-420) Upgrade Spring Boot 3.4.5 to fix security issues (CVE-2025-22235, CVE-2025-22234)
Referring to https://ci-platform.companieshouse.gov.uk/teams/team-development/pipelines/penalty-payment-web/jobs/dependency-check/builds/219
* https://spring.io/security/cve-2025-22235 -> spring-boot 3.4.5
* https://spring.io/security/cve-2025-22234 -> spring-security-crypto 6.4.5
See also Spring Boot 3.4.5 - https://docs.spring.io/spring-boot/appendix/dependency-versions/coordinates.html
[SAN-420]: https://companieshouse.atlassian.net/browse/SAN-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAN-420 Upgrade Spring Boot 3.4.5 to fix security issues (CVE-2025-22235, CVE-2025-22234)

- pom.xml
[SAN-462](https://companieshouse.atlassian.net/browse/SAN-462) Upgrade to Spring Boot 3.5.0 (CVE-2025-22233, CVE-2025-41232)
(cherry picked from commit 7a5a6cf043bbd2a48c5c23ca539ef076cb89ba1e)
[SAN-462]: https://companieshouse.atlassian.net/browse/SAN-462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAN-462 [Austin release 2.1] Upgrade to Spring Boot 3.5.0 (CVE-2025-22233, CVE-2025-41232)

- README.md
- src/main/resources/application.properties
[SAN-484](https://companieshouse.atlassian.net/browse/SAN-484) Remove the redundant environment variable PENALTY_PAYMENT_MATOMO_START_NOW_BUTTON_GOAL_ID
[SAN-484]: https://companieshouse.atlassian.net/browse/SAN-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAN-484 Remove the redundant environment variable PENALTY_PAYMENT_MATOMO_START_NOW_BUTTON_GOAL_ID

- pom.xml
SAN-553
CVE-2024-7246 - grpc-api dependency update
Update version api-sdk-java
https://companieshouse.atlassian.net/browse/SAN-553
> SAN-553 CVE fix

- src/main/java/uk/gov/companieshouse/web/pps/service/penaltyrefstartswith/impl/PenaltyRefStartsWithServiceImpl.java
- src/main/java/uk/gov/companieshouse/web/pps/service/viewpenalty/impl/ViewPenaltiesServiceImpl.java
Adding the sign out option back into penalty summary page, not needed for penalty ref starts with page:
https://companieshouse.atlassian.net/browse/SAN-556
> SAN-556-Missing-Sign-Out-Bug

- src/main/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PenaltyPaymentServiceImpl.java
- src/test/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PenaltyPaymentServiceImplTest.java
When a call to fetch penalties for a given penalty ref returns a paid penalty and an associated cost with the same ID, the user is redirected to pay by BACS page as payment for penalties with associated costs are not processed by PPS.
However, since the penalty is already paid, we expect to see the message that the penalty is already paid.
This patch applies the required fix that enables the expected message already paid penalties to be presented to the user.
> SAN-597 Address the issue with paid penalty with associated costs

- pom.xml
[SAN-666](https://companieshouse.atlassian.net/browse/SAN-666) Fix jib-maven-plugin version: 3.4.6
[SAN-666]: https://companieshouse.atlassian.net/browse/SAN-666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAN-666 Fix jib-maven-plugin version: 3.4.6
