src/main/resources/templates/lfp/home.html

Change the table for alternative ways to pay to a list for screen readers to navigate more easily. 
Resolves: LFA-1068

Fix homepage table view of alternative ways to pay for screen readers

---

src/main/resources/templates/layouts/baseLayout.html

Update CDN path

---

src/main/resources/templates/lfp/home.html

change piwik event to goal

---

src/main/java/uk/gov/companieshouse/web/lfp/controller/lfp/ConfirmationController.java
src/main/resources/templates/lfp/confirmationPage.html

Change the confirmation page wording and displayed reference numbers. 
Resolves: LFA-1312

Change wording for reference numbers on confirmation page

---

src/main/java/uk/gov/companieshouse/web/lfp/service/payment/impl/PaymentServiceImpl.java

Temporary increase in logging - to be reverted

Increase logging to assist with debugging

---

src/main/resources/templates/lfp/details.html

add id to summary attribute
add aria-labelledby tag to govuk-details attribute

add aria-labelledby tag and id to summary

---

README.md
src/main/resources/application.properties
src/main/resources/templates/lfp/home.html

-Change the LFP home screen (/late-filing-penalty) to mimic the gov-uk home screen as per LFP enhancements work request.
-Add Appeal URL to the home screen.
-Add dynamic variables used in the HTML home screen for CH Banking details

Change LFP home page to mirror gov-uk page as requested

---

src/main/resources/templates/lfp/home.html

Fix title issues

---

src/main/resources/templates/lfp/home.html

Add matomo tracking to appeals link

---

src/main/resources/templates/lfp/home.html

Remove the s from accounts

---

src/main/resources/templates/lfp/home.html

-As requested, the phone section of the home page has been removed.

remove phone section from the home page

---

src/main/resources/templates/lfp/home.html

-Update the header and the sub header to match GDS.

update headers to match GDS

---

src/main/resources/templates/lfp/home.html

-Added overseas information to the home page.
-Made needed adjustments to make it display correctly.

update home page to show overseas payment info

---

src/main/resources/templates/lfp/home.html

Change to <a> tag with mail:to attribute.

fix lfp email display

---

pom.xml
src/main/resources/application.properties
src/main/resources/templates/layouts/baseLayout.html

Part of 3 PR's that make up the PoC for Cookie Consent in CHS. The other PR's are in cdn.ch.gov.uk and common-web-java.
This PR adds the cookie consent banner which determines if piwik runs or not.

Adds new fragments for cookie consent banner

---

src/main/resources/templates/lfp/home.html
src/main/resources/templates/lfp/onlinePaymentUnavailable.html

Resolves: [BI-9379](https://companieshouse.atlassian.net/browse/BI-9379)
Adding IBAN details and bank details to payment information details on home page and payment unavailable

Adding IBAN details and other bank details

---

pom.xml

Resolves [BI-9764](https://companieshouse.atlassian.net/browse/BI-9764)
Adding google plugin to enable lfp-pay-web to work with Docker

Add google plugin for docker

---

pom.xml

ticket: https://companieshouse.atlassian.net/browse/BI-9675 
updated parent pom to use version 1.3
updated spring-test version to 2.5.3 to fix issues with parent-pom

Updated ch-parent pom to 1.3

---

pom.xml

Resolves [DEBT-1454](https://companieshouse.atlassian.net/browse/DEBT-1454)
Adding in changes for structured logging dependencies as well as org.json library dependency to fix logj4 vulnerability.

Update log4j dependencies

---

pom.xml

Resolves [DEBT-1558](https://companieshouse.atlassian.net/browse/DEBT-1558)
Upgrading structured logging to 1.9.11 as well as upgrading Log4J Bom version to 1.17.0

Upgrading structured logging to 1.9.11 and Log4J 1.17.0

---

src/main/resources/templates/lfp/home.html
src/main/resources/templates/lfp/onlinePaymentUnavailable.html
src/main/resources/templates/lfp/serviceUnavailable.html

Resolves  [BI-10449](https://companieshouse.atlassian.net/browse/BI-10449)
Amending `home`, `online-payment-unavailable` & `service-unavailable screen`  to remove pay-by-phone details and amending account number on IBAN to display the correct number

Feature/BI-10449 amend IBAN details remove pay by phone

---

src/main/resources/templates/layouts/baseLayout.html

Jira ticket: https://companieshouse.atlassian.net/browse/BI-12129
Implement idle sign out in the lfp pay service

add script which causes idle sign out to base layout

---

src/main/java/uk/gov/companieshouse/web/lfp/controller/lfp/ConfirmationController.java
src/main/java/uk/gov/companieshouse/web/lfp/controller/lfp/EnterLFPDetailsController.java
src/main/java/uk/gov/companieshouse/web/lfp/controller/lfp/LFPStartController.java
src/main/java/uk/gov/companieshouse/web/lfp/controller/lfp/SignOutController.java
src/main/java/uk/gov/companieshouse/web/lfp/controller/lfp/ViewPenaltiesController.java
src/main/java/uk/gov/companieshouse/web/lfp/service/latefilingpenalty/impl/LateFilingPenaltyServiceImpl.java
src/main/java/uk/gov/companieshouse/web/lfp/service/latefilingpenalty/impl/PayableLateFilingPenaltyServiceImpl.java
src/main/java/uk/gov/companieshouse/web/lfp/validation/AllowlistChecker.java

Resolves [BI-12376](https://companieshouse.atlassian.net/browse/BI-12376) 
Add and tidy up logs it is clearer so that current processes and errors are clearer when logs appear in Kibana.
[BI-12376]: https://companieshouse.atlassian.net/browse/BI-12376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BI-12376- improve logs across service

---

pom.xml

Related Ticket :- https://companieshouse.atlassian.net/browse/IE-254
Bumped up versions for web-security-java and java-session-handler in attempt to fix the staging bug.

upped version for java session handler and web security

---

pom.xml

Related Ticket: https://companieshouse.atlassian.net/browse/IE-254
Changing java-session-handler version to 2.2.4

change to 2.2.4

---

pom.xml

This reverts commit 46e829c7f600a4ec10d73096287f81771fe216e1.

Revert "upped version for java session handler and web security"

---

pom.xml
src/test/java/uk/gov/companieshouse/web/lfp/security/WebsecurityTests.java

Created Unit Test case for class WebSecurity to pass sonar gate

WebSecurity Testcase covered 

---

src/main/resources/templates/pps/home.html

SAN-28: Update Pay Penalty Page

---

pom.xml

Update versions of vulnerable packages

SAN-136: Update versions of vulnerable packages

---

src/main/java/uk/gov/companieshouse/web/pps/PPSWebApplication.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferPenaltyReferenceController.java
src/main/java/uk/gov/companieshouse/web/pps/models/AvailablePenaltyReference.java
src/main/java/uk/gov/companieshouse/web/pps/models/PenaltyReferenceChoice.java
src/main/java/uk/gov/companieshouse/web/pps/security/WebSecurity.java
src/main/java/uk/gov/companieshouse/web/pps/util/PenaltyReference.java
src/main/resources/templates/fragments/ppsGlobalErrors.html
src/main/resources/templates/layouts/baseLayout.html
src/main/resources/templates/pps/bankTransferPenaltyReference.html
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferPenaltyReferenceControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/security/WebsecurityTests.java

Set up Pay via BACS selection page

SAN-71 Pay via BACS selection page set up

---

src/main/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferSanctionsDetailsController.java
src/main/resources/templates/pps/bankTransferSanctionsDetails.html
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferSanctionsDetailsControllerTest.java

Pay via BACs Sanctions Details page set up

SAN-74 Pay by bank transfer Sanctions Details

---

src/main/resources/templates/pps/penaltyPaid.html

SAN-26-LFP-Penalty-Already-Paid Updating penaltyPaid.html

SAN-26-LFP-Penalty-Already-Paid Updating penaltyPaid.html

---

pom.xml

[SAN-33](https://companieshouse.atlassian.net/browse/SAN-33) Update jib latest image to be shared-services-ecr-eu-west-2-ro as seen in penalty-payment-web-ecr
[SAN-33]: https://companieshouse.atlassian.net/browse/SAN-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SAN-33 Update jib latest image to be shared-services-ecr-eu-west-2-ro as seen in penalty-payment-web-ecr

---

src/main/resources/application.properties
src/main/resources/templates/pps/confirmationPage.html

[SAN-142](https://companieshouse.atlassian.net/browse/SAN-142) Add pay another penalty link to confirmation page using property: `penalty.ref-starts-with-url`
[SAN-142]: https://companieshouse.atlassian.net/browse/SAN-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SAN-142 Add pay another penalty link to confirmation page using property: penalty.ref-starts-with-url

---

src/main/java/uk/gov/companieshouse/web/pps/annotation/Penalty.java
src/main/java/uk/gov/companieshouse/web/pps/config/MessageConfig.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/EnterDetailsController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/PenaltyRefStartsWithController.java
src/main/java/uk/gov/companieshouse/web/pps/models/EnterDetails.java
src/main/resources/ValidationMessages.properties
src/main/resources/locales/messages.properties
src/main/resources/templates/pps/details.html
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/EnterDetailsControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/PenaltyRefStartsWithControllerTest.java

[SAN-18](https://companieshouse.atlassian.net/browse/SAN-18) Update Penalty details page for sanctions display using new message bundle
[SAN-18]: https://companieshouse.atlassian.net/browse/SAN-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SAN-18 Update Penalty details page for sanctions display using new message bundle

---

src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ConfirmationController.java
src/main/resources/templates/pps/confirmationPage.html
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/ConfirmationControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/util/PPSTestUtility.java

LFP - Confirmation page Development

SAN-24 LFP - Confirmation page

---

src/main/java/uk/gov/companieshouse/web/pps/controller/pps/OnlinePaymentUnavailableController.java
src/main/resources/templates/pps/onlinePaymentUnavailable.html

Updating onlinePaymentUnavailable.html

SAN-137-LFP-Unable-to-pay Updating onlinePaymentUnavailable.html

---

src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ConfirmationController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ViewPenaltiesController.java
src/main/java/uk/gov/companieshouse/web/pps/service/payment/PaymentService.java
src/main/java/uk/gov/companieshouse/web/pps/service/payment/impl/PaymentServiceImpl.java
src/main/java/uk/gov/companieshouse/web/pps/service/penaltypayment/PayablePenaltyService.java
src/main/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PayablePenaltyServiceImpl.java
src/main/resources/templates/pps/confirmationPage.html
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/ConfirmationControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/ViewPenaltiesControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/service/payment/impl/PaymentServiceImplTest.java
src/test/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PayablePenaltyServiceImplTest.java

- Update PaymentService method, createPaymentSession, to require penalty reference
- Update GET Confirmation endpoint to include payment reference as well as penalty reference
- Update Redirect URL for payment session to match the updated confirmation endpoint

SAN-177 Update confirmation page with penalty reference

---

src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ViewPenaltiesController.java
src/main/java/uk/gov/companieshouse/web/pps/util/PenaltyUtils.java
src/main/resources/locales/messages.properties
src/main/resources/templates/pps/viewPenalties.html
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/ViewPenaltiesControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/util/PenaltyUtilsTest.java

SAN-135 change terminology to penalty reference instead of reference number

SAN-135 Change terminology to penalty reference instead of reference number

---

README.md
src/main/java/uk/gov/companieshouse/web/pps/util/PenaltyReference.java
src/main/java/uk/gov/companieshouse/web/pps/validation/EnterDetailsValidator.java
src/main/resources/locales/messages.properties
src/main/resources/templates/pps/bankTransferSanctionsDetails.html
src/main/resources/templates/pps/details.html
src/test/java/uk/gov/companieshouse/web/pps/util/PenaltyReferenceTest.java
src/test/java/uk/gov/companieshouse/web/pps/validation/EnterDetailsValidatorTest.java

[SAN-197](https://companieshouse.atlassian.net/browse/SAN-197) Update SANCTIONS Penalty Ref - This starts with P, followed by 7 numbers. For example, P1234567.
[SAN-197]: https://companieshouse.atlassian.net/browse/SAN-197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SAN-197 Update SANCTIONS Penalty Ref - This starts with P, followed by 7 numbers. For example, P1234567.

---

pom.xml
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/AccessibilityStatementControllerTest.java

Set log4j version to latest rc
Update SpringBoot to fix transitive dependencies issues
Fix test that had incorrect trailing slash

SAN-179: Set log4j version to latest rc and update SpringBoot

---

src/main/resources/application.properties
src/main/resources/templates/pps/serviceUnavailable.html

Updated serviceUnavailable.html for when service is down for scheduled maintenance

SAN-139-STOP-service-down-scheduled updating serviceUnavailable.html

---

src/main/java/uk/gov/companieshouse/web/pps/controller/BaseController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/AccessibilityStatementController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferLateFilingDetailsController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferPenaltyReferenceController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferSanctionsDetailsController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ConfirmationController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/DcaRequiredController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/OnlinePaymentUnavailableController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/PenaltyRefStartsWithController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/SignOutController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/StartController.java
src/main/resources/templates/pps/accessibilityStatement.html
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/AccessibilityStatementControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/BankTransferPenaltyReferenceControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/ConfirmationControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/DcaRequiredControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/EnterDetailsControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/OnlinePaymentUnavailableControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/PenaltyPaidControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/PenaltyRefStartsWithControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/StartControllerTest.java

SAN-166 Logged in user header bar no longer displayed in CIDEV or LOCAL Environments
Update after QA testing:
Changes for user bar showing when user log in to every page

SAN-166 Update on Logged in user header bar

---

README.md

[SAN-196](https://companieshouse.atlassian.net/browse/SAN-196) Update README with new env variables for Matomo Goal Ids
[SAN-196]: https://companieshouse.atlassian.net/browse/SAN-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SAN-196 Update README with new env variables for Matomo Goal Ids

---

src/main/java/uk/gov/companieshouse/web/pps/controller/BaseController.java
src/main/resources/templates/pps/confirmationPage.html

SAN-202 Update Feedback links

---

src/main/resources/templates/fragments/header.html

Fixing size and width of new service banner

SAN-167-Service-Banner-fix fixing size and width of banner

---

src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ConfirmationController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ViewPenaltiesController.java
src/main/java/uk/gov/companieshouse/web/pps/util/PenaltyUtils.java
src/main/resources/application.properties
src/main/resources/locales/messages.properties
src/main/resources/templates/pps/confirmationPage.html
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/ConfirmationControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/ViewPenaltiesControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/util/PenaltyUtilsTest.java

* Updated confirmation controller to support CS penalties
* Updated confirmation page to support CS penalties

SAN-21 Set up Confirmation page for CS penalties

---

src/main/resources/templates/fragments/header.html

Updating header.html to fix blue line bug for service banner

SAN-249-Blue-Line-Header-Bug Updating header.html to fix blue line

---

src/main/resources/templates/pps/home.html

Updating home.html abilitynet link

SAN-245-Update-Ability-Link Updating home.html abilitynet link

---

src/main/resources/application.properties

setting penalty-ref-enabled to true in application.properties.

SAN-227-Add-Penalty-Type-Page setting penalty-ref-enabled to true

---

src/main/resources/templates/pps/details.html
src/main/resources/templates/pps/home.html

Updating home.html and details.html titles

SAN-263-Tab-Names-PPS Updating home.html and details.html titles

---

src/main/resources/templates/pps/bankTransferLateFilingDetails.html
src/main/resources/templates/pps/bankTransferSanctionsDetails.html

Updating bankTransferLateFilingDetails.html and bankTransferSanctionsDetails.html tab names

SAN-263-Tab-Names-PPS Updating tab names

---

src/main/resources/templates/fragments/header.html

Updating header.html link of logo

SAN-255-GovUK-Logo-Redirect Updating header.html link of logo

---

src/main/resources/templates/pps/confirmationPage.html

fixing confirmationPage.html contact us link

SAN-286-Contact-Us-Link-Bug fixing confirmationPage.html contact us link

---

src/main/java/uk/gov/companieshouse/web/pps/controller/pps/EnterDetailsController.java
src/main/java/uk/gov/companieshouse/web/pps/validation/EnterDetailsValidator.java
src/main/resources/templates/pps/details.html

SAN-239 Penalty details field changes

SAN-239 Penalty details field changes

---

src/main/resources/templates/pps/confirmationPage.html

SAN-287 Confirmation page next steps section

SAN-287 Confirmation page next steps section

---

src/main/resources/templates/pps/penaltyPaid.html

removing company name from matomo and changing ids to penalty-paid in penaltyPaid.html

SAN-306-Matomo-Remove-Company-Name

---

pom.xml
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/EnterDetailsController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ViewPenaltiesController.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/EnterDetailsControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/PenaltyPaidControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/ViewPenaltiesControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/util/PPSTestUtility.java

[SAN-237](https://companieshouse.atlassian.net/browse/SAN-237) Update EnterDetailsController / ViewPenaltiesController to check for PayableStatus.CLOSED after get-penalties
* api-sdk-java 6.0.37
[SAN-237]: https://companieshouse.atlassian.net/browse/SAN-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SAN-237 Update EnterDetailsController / ViewPenaltiesController to check for PayableStatus.CLOSED

---

README.md
src/main/resources/application.properties
src/main/resources/templates/pps/details.html

Adding matomo to the penalty details page.

SAN-295-200-Matomo-Penalty-Details matomo for penalty details page

---

src/main/java/uk/gov/companieshouse/web/pps/PPSWebApplication.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ConfirmationController.java
src/main/java/uk/gov/companieshouse/web/pps/exception/GlobalExceptionHandler.java
src/main/java/uk/gov/companieshouse/web/pps/interceptor/UserDetailsInterceptor.java
src/main/java/uk/gov/companieshouse/web/pps/service/company/impl/CompanyServiceImpl.java
src/main/java/uk/gov/companieshouse/web/pps/service/payment/impl/PaymentServiceImpl.java
src/main/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PayablePenaltyServiceImpl.java
src/main/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PenaltyPaymentServiceImpl.java
src/test/java/uk/gov/companieshouse/web/pps/interceptor/UserDetailsInterceptorTests.java
src/test/java/uk/gov/companieshouse/web/pps/service/company/impl/CompanyServiceImplTest.java
src/test/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PayablePenaltyServiceImplTest.java
src/test/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PenaltyPaymentServiceImplTest.java
src/test/java/uk/gov/companieshouse/web/pps/validation/AllowListCheckerTest.java

[SAN-335](https://companieshouse.atlassian.net/browse/SAN-335) Sonarqube: Fix remaining Clean Code / Software Quality issues
* java:S6813 Field dependency injection should be avoided
* java:S6353 Regular expression quantifiers and character classes should be used concisely
* java:S1130 Exceptions in "throws" clauses should not be superfluous
[SAN-335]: https://companieshouse.atlassian.net/browse/SAN-335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SAN-335 Sonarqube: Fix remaining Clean Code / Software Quality issues

---

routes.yaml
src/main/java/uk/gov/companieshouse/web/pps/PPSWebApplication.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/StartController.java
src/main/java/uk/gov/companieshouse/web/pps/security/WebSecurity.java
src/test/java/uk/gov/companieshouse/web/pps/PPSWebApplicationTest.java
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/StartControllerTest.java
src/test/java/uk/gov/companieshouse/web/pps/security/WebSecurityTests.java
terraform/groups/ecs-service/locals.tf

Add GDS path to enable routing to the start page

SAN-336: Add GDS path to enable routing to the start page

---

src/main/java/uk/gov/companieshouse/web/pps/validation/AllowlistChecker.java
src/test/java/uk/gov/companieshouse/web/pps/validation/AllowListCheckerTest.java

Update regex to enable signout to return to originator page

SAN-325: Update regex to enable signout to return to originator page

---

pom.xml
src/main/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PayablePenaltyServiceImpl.java
src/main/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PenaltyPaymentServiceImpl.java
src/test/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PayablePenaltyServiceImplTest.java
src/test/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PenaltyPaymentServiceImplTest.java
src/test/java/uk/gov/companieshouse/web/pps/util/PPSTestUtility.java

* Bump api-sdk-java version to 6.2
* Update API paths
Depends on:
https://github.com/companieshouse/penalty-payment-api/pull/70

SAN-66 Update penalty-payment-api paths

---

pom.xml

SAN-368: Fix CVEs

---

pom.xml
src/test/java/uk/gov/companieshouse/web/pps/util/PPSTestUtility.java

[SAN-265](https://companieshouse.atlassian.net/browse/SAN-265) Update PayableFinancialPenalties to rename company_number to customer_code
[SAN-265]: https://companieshouse.atlassian.net/browse/SAN-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SAN-265 Update PayableFinancialPenalties to rename company_number to customer_code

---

src/main/resources/locales/messages.properties
src/main/resources/templates/pps/confirmationPage.html
src/main/resources/templates/pps/details.html
src/main/resources/templates/pps/onlinePaymentUnavailable.html
src/main/resources/templates/pps/penaltyPaid.html
src/main/resources/templates/pps/penaltyRefStartsWith.html
src/main/resources/templates/pps/serviceUnavailable.html
src/main/resources/templates/pps/signOut.html
src/main/resources/templates/pps/unscheduledServiceDown.html
src/main/resources/templates/pps/viewPenalties.html

https://companieshouse.atlassian.net/browse/SAN-291
Updating the tab names for multiple html files

SAN-291-Updating-Tab-names Updating multiple tab names

---

src/main/resources/ValidationMessages.properties
src/main/resources/locales/messages.properties
src/main/resources/templates/pps/details.html
src/test/java/uk/gov/companieshouse/web/pps/validation/EnterDetailsValidatorTest.java

updating reference number to penalty reference on details.html
https://companieshouse.atlassian.net/browse/SAN-329

SAN-329-LFP-Penalty-Reference-Penalty-Details

---

src/main/resources/locales/messages.properties
src/main/resources/templates/pps/details.html

fixes wording on the enter details page, above image:
https://companieshouse.atlassian.net/browse/SAN-387

SAN-387-Updating-penalty-details-LFP-wording

---

src/main/resources/templates/layouts/baseLayout.html
src/main/resources/templates/pps/bankTransferPenaltyReference.html

Removing index for bankTransferPenaltyReference.html
https://companieshouse.atlassian.net/browse/SAN-354

SAN-354-Remove-indexing-BACS-page

---

src/main/resources/templates/fragments/header.html
src/main/resources/templates/pps/onlinePaymentUnavailable.html
src/main/resources/templates/pps/penaltyRefStartsWith.html
src/main/resources/templates/pps/serviceUnavailable.html
src/main/resources/templates/pps/signOut.html
src/main/resources/templates/pps/unscheduledServiceDown.html
src/main/resources/templates/pps/viewPenalties.html

This PR fixes the alerts and errors that were found when testing the system with the WAVE tool, further information can be found here:
https://companieshouse.atlassian.net/browse/SAN-429
https://companieshouse.atlassian.net/wiki/spaces/NS/pages/5367595091/WAVE+Tool+Accessibility+Testing

SAN-429-Accessibility-Testing-Changes

---

src/main/resources/templates/pps/onlinePaymentUnavailable.html

Linked PR:
https://github.com/companieshouse/docker-chs-development/pull/1809

SAN-27 Stop screen for ROE

---

README.md
src/main/resources/application.properties
src/main/resources/templates/pps/details.html
src/main/resources/templates/pps/onlinePaymentUnavailable.html
src/main/resources/templates/pps/penaltyRefStartsWith.html

Adding ROE Matomo config to penalty-payment-web
JIRA Ticket:
https://companieshouse.atlassian.net/browse/SAN-467
Linked PRs:
https://github.com/companieshouse/ecs-service-configs-dev/pull/1365
https://github.com/companieshouse/docker-chs-development/pull/1810

SAN-467-ROE-Matomo

---

src/main/resources/templates/pps/serviceUnavailable.html
src/main/resources/templates/pps/unscheduledServiceDown.html

SAN-469 Wording updates for scheduled, and unscheduled maintenance
https://companieshouse.atlassian.net/browse/SAN-469

SAN-469 Wording updates for scheduled, and unscheduled maintenance

---

src/main/java/uk/gov/companieshouse/web/pps/controller/pps/StartController.java
src/main/resources/templates/pps/serviceUnavailable.html
src/main/resources/templates/pps/unscheduledServiceDown.html
src/test/java/uk/gov/companieshouse/web/pps/controller/pps/StartControllerTest.java

SAN-469 Follow up work for Wording updates for scheduled, and unscheduled maintenance in order to align to prototype version 10 
https://companieshouse.atlassian.net/browse/SAN-469

SAN-469 Wording updates for scheduled, and unscheduled maintenance follow up

---

src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ConfirmationController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/EnterDetailsController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/PenaltyRefStartsWithController.java
src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ViewPenaltiesController.java
src/main/java/uk/gov/companieshouse/web/pps/service/company/impl/CompanyServiceImpl.java
src/main/java/uk/gov/companieshouse/web/pps/service/payment/impl/PaymentServiceImpl.java
src/main/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PayablePenaltyServiceImpl.java
src/main/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PenaltyPaymentServiceImpl.java

Added some debug logging to aid debugging.

SAN-383 Improve logging

---

pom.xml
src/main/java/uk/gov/companieshouse/web/pps/util/PenaltyUtils.java
src/main/java/uk/gov/companieshouse/web/pps/validation/EnterDetailsValidator.java

SAN-529
Update dependency check on penalty-payment-web pipeline
https://companieshouse.atlassian.net/browse/SAN-529

SAN-529 Update dependency check on penalty-payment-web pipeline

---

src/main/java/uk/gov/companieshouse/web/pps/controller/BaseController.java

SAN-555
Sign out from penalty paid page redirects to error for page not found
https://companieshouse.atlassian.net/browse/SAN-555

SAN-555 Sign out from penalty paid page redirects to error for page not found

---

pom.xml

SAN-566
CVE-2025-52520, CVE-2025-53506 tomcat-embed-core-10.1.42
https://companieshouse.atlassian.net/browse/SAN-566

SAN-566 Update dependency for CVE

---

src/main/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PenaltyPaymentServiceImpl.java
src/test/java/uk/gov/companieshouse/web/pps/service/penaltypayment/impl/PenaltyPaymentServiceImplTest.java

SAN-559
Adding checking for unscheduled maintenance service down

SAN-559 Adding checking for unschedule maintenance

---

pom.xml

SAN-600
CVE-2025-48989, CVE-2025-41242 - Update Spring Boot
https://companieshouse.atlassian.net/browse/SAN-600

SAN-600 Fix CVE update Spring Boot Version

---

src/main/resources/locales/messages.properties
src/test/java/uk/gov/companieshouse/web/pps/validation/EnterDetailsValidatorTest.java

Changing "AB" to "SC" in help text on the enter details page for LFP and Sanctions journey.
Linked to:
https://companieshouse.atlassian.net/browse/SAN-587

SAN-587-Updating-Help-Text

---

src/main/resources/templates/pps/serviceUnavailable.html
src/main/resources/templates/pps/unscheduledServiceDown.html

SAN-591
Duplicate headings in maintenance windows
https://companieshouse.atlassian.net/browse/SAN-591

SAN-591 Duplicate headings in maintenance windows
